---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: ''
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/covers-keep-all-the-crows-away-banti-buli.md
- projects/covers-keep-all-the-crows-away-banti-buli.md
- projects/pickle-dill-picks-boxes.md
- projects/pickle-dill-picks-boxes.md
- projects/spring-from-my-bedroom.md
- projects/spring-from-my-bedroom.md
