---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- type: text
  name: hero_img
  label: Hero image
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
- name: hero_content
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: title
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: text
  config:
    min: 
    max: 
    labelField: 
  label: hero content
pages:
- data/theme.json
- data/theme.json
